# Model
device: 0

name: /scratch2/mas/jiangkailin/MMKE/opt-2.7b
model_name: blip2
model_class: Blip2OPT
small_name: /scratch2/mas/jiangkailin/MMKE/opt-125m
tokenizer_class: GPT2Tokenizer
tokenizer_name: /scratch2/mas/jiangkailin/MMKE/opt-2.7b
# cls_name: hugging_cache/distilbert-base-cased
cls_name: /scratch2/nlp/plm/distilbert-base-uncased
cls_class: AutoModel 
inner_params:
- opt_model.model.decoder.layers.29.fc1.weight
- opt_model.model.decoder.layers.29.fc2.weight
- opt_model.model.decoder.layers.30.fc1.weight
- opt_model.model.decoder.layers.30.fc2.weight
- opt_model.model.decoder.layers.31.fc1.weight
- opt_model.model.decoder.layers.31.fc2.weight

# Method
alg: SERAC_MULTI
lr: 1e-5
edit_lr: 1e-2
seed: 0
lr_lr: 0.0
cedit: 0.1
iedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
final_eval: True
supervised: False
train_base: False
no_grad_layers: null
soft_weighting: False
checkpoint_grad: False
cross_attend: False
cos: False
freeze: null
square: True
bound_embeds: False
use_all_negatives: False
freeze_cntr: False
dist_heads: 1
lora: null
archive: null

batch_size: 1
model_save_pt: 3000
edit_bs: 1
silent: False
#max_epochs: 1
max_iters: 30000
log_interval: 100
val_interval: 3000
early_stop_patience: 3000
early_stop_key: "loss/total_edit_val"
eval_only: False
half: False
save: False
debug: False
log_errors: False
unlikelihood: True


val_batch_size: 1
accumulate_bs: 1
val_steps: 500
opt: Adam
grad_clip: 100.

# Output
results_dir: ./results-new/entity

# Multimodal
qformer_checkpoint: /scratch2/mas/jiangkailin/MMKE/blip2_pretrained_opt2.7b/blip2_pretrained_opt2.7b.pth
qformer_name_or_path: /scratch2/nlp/plm/bert-base-uncased
state_dict_file: /scratch2/mas/jiangkailin/MMKE/eva_vit_g/eva_vit_g.pth

coco_image: data_image
rephrase_image: data_image



# # Model
# device: 0

# name: /home/jiangkailin/datacheckpoint/checkpoint/MMKE/opt-2.7b
# # name: null
# model_name: blip2
# model_class: Blip2OPT
# small_name: /home/jiangkailin/datacheckpoint/checkpoint/MMKE/opt-125m
# tokenizer_class: GPT2Tokenizer
# tokenizer_name: /home/jiangkailin/datacheckpoint/checkpoint/MMKE/opt-2.7b
# cls_name: /home/jiangkailin/datacheckpoint/checkpoint/MMKE/bert-base-uncased/
# cls_class: AutoModel 
# inner_params:
# - opt_model.model.decoder.layers.29.fc1.weight
# - opt_model.model.decoder.layers.29.fc2.weight
# - opt_model.model.decoder.layers.30.fc1.weight
# - opt_model.model.decoder.layers.30.fc2.weight
# - opt_model.model.decoder.layers.31.fc1.weight
# - opt_model.model.decoder.layers.31.fc2.weight

# # Method
# alg: SERAC_MULTI
# lr: 1e-5
# edit_lr: 1e-2
# seed: 0
# lr_lr: 0.0
# cedit: 0.1
# iedit: 0.1
# cloc: 1.0
# cbase: 1.0
# dropout: 0.0
# final_eval: True
# supervised: False
# train_base: False
# no_grad_layers: null
# soft_weighting: False
# checkpoint_grad: False
# cross_attend: False
# cos: False
# freeze: null
# square: True
# bound_embeds: False
# use_all_negatives: False
# freeze_cntr: False
# dist_heads: 1
# lora: null
# archive: null

# batch_size: 1
# # model_save_pt: 5000
# model_save_pt: 100
# edit_bs: 1
# silent: False
# #max_epochs: 1
# # max_iters: 50000
# max_iters: 1000
# log_interval: 100
# # val_interval: 5000
# val_interval: 100
# early_stop_patience: 50000
# early_stop_key: "loss/total_edit_val"
# eval_only: False
# half: False
# save: False
# debug: False
# log_errors: False
# unlikelihood: True


# val_batch_size: 1
# accumulate_bs: 1
# val_steps: 500
# opt: Adam
# grad_clip: 100.

# # Output
# results_dir: ./results

# # Multimodal
# qformer_checkpoint: /home/jiangkailin/datacheckpoint/checkpoint/MMKE/blip2_pretrained_opt2.7b/blip2_pretrained_opt2.7b.pth
# qformer_name_or_path: /home/jiangkailin/datacheckpoint/checkpoint/MMKE/bert-base-uncased/
# state_dict_file: /home/jiangkailin/datacheckpoint/checkpoint/MMKE/eva_vit_g//eva_vit_g.pth

# # # image
# # coco_image: /home/jiangkailin/project/VLKEB/visual_knowledge_image_data
# # rephrase_image: /home/jiangkailin/project/VLKEB/visual_knowledge_image_data


# # image
# coco_image: /home/jiangkailin/project/VLKEB/image_data
# rephrase_image: /home/jiangkailin/project/VLKEB/image_data