# Model
device: 0

name: /scratch2/nlp/plm/Qwen-VL
model_name: qwen-vl
model_class: qwen-vl
tokenizer_class: QWenTokenizer
tokenizer_name: /scratch2/nlp/plm/Qwen-VL
inner_params:
- transformer.h.29.mlp.w1.weight
- transformer.h.29.mlp.w2.weight
- transformer.h.29.mlp.c_proj.weight
- transformer.h.30.mlp.w1.weight
- transformer.h.30.mlp.w2.weight
- transformer.h.30.mlp.c_proj.weight
- transformer.h.31.mlp.w1.weight
- transformer.h.31.mlp.w2.weight
- transformer.h.31.mlp.c_proj.weight

# Method
alg: MEND
lr: 1e-6
edit_lr: 1e-4
lr_lr: 1e-4
seed: 42
cedit: 0.1
iedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
train_base: False
no_grad_layers: null
one_sided: False
n_hidden: 1
hidden_dim: null
init: id
norm: True
combine: True
x_only: False
delta_only: False
act: relu
rank: 1920
mlp_class: IDMLP
shared: True
archive: null

# Train
batch_size: 1
model_save_pt: 5000
silent: False
#max_epochs: 1
max_iters: 50000
log_interval: 100
eval_log_interval: 1000
final_eval: True
val_interval: 1000
early_stop_patience: 20000
early_stop_key: "loss/total_edit_val"
eval_only: False
half: False
debug: False
save: Falses
verbose: True

val_batch_size: 1
accumulate_bs: 2
val_steps: 500 # only for debug
opt: Adam
grad_clip: 100.

# Output
results_dir: ./results

# Multimodal
qformer_checkpoint: null
qformer_name_or_path: null
state_dict_file: null
pretrained_ckpt: null

# image
coco_image: data_image
rephrase_image: data_image