# Model
device: 0

name: hugging_cache/mplug-owl2-llama2-7b 
model_name: owl-2
model_class: owl-2
small_name: hugging_cache/llama-7b/
tokenizer_class: LlamaTokenizer
tokenizer_name: hugging_cache/mplug-owl2-llama2-7b 
cls_name: hugging_cache/distilbert-base-cased/
cls_class: AutoModel 
inner_params:
- model.layers.29.mlp.down_proj.weight
- model.layers.29.mlp.up_proj.weight
- model.layers.30.mlp.down_proj.weight
- model.layers.30.mlp.up_proj.weight
- model.layers.31.mlp.down_proj.weight
- model.layers.31.mlp.up_proj.weight


# Method
alg: SERAC_MULTI
lr: 1e-5
edit_lr: 1e-2
seed: 0
lr_lr: 0.0
cedit: 0.1
iedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
final_eval: True
supervised: False
train_base: False
no_grad_layers: null
soft_weighting: False
checkpoint_grad: False
cross_attend: False
cos: False
freeze: null
square: True
bound_embeds: False
use_all_negatives: False
freeze_cntr: False
dist_heads: 1
lora: null
archive: None

batch_size: 1
model_save_pt: 5000
edit_bs: 1
silent: False
#max_epochs: 1
max_iters: 50000
log_interval: 200
val_interval: 5000
early_stop_patience: 5000
early_stop_key: "loss/total_edit_val"
eval_only: True
half: False
save: False
debug: False
log_errors: False
unlikelihood: True


val_batch_size: 1
accumulate_bs: 1
val_steps: 1000
opt: Adam
grad_clip: 100.

# Output
results_dir: ./results

# Multimodal
qformer_checkpoint: None
qformer_name_or_path: None
state_dict_file: None

coco_image: data_image
rephrase_image: data_image